from services.auth_service import auth_service
from services.game_service import game_service
from services.speech_service import speech_service
from services.phoneme_analyzer_service import phoneme_service
from services.user_service import user_service